### ISSUE TITLE
`erc20-deploy.js` fails

### ISSUE THREAD

**Issue by egonspace** [klaytn/sc-vt#10]
`erc20-deploy.js` fails like this.

```
$ node erc20-deploy.js          

------------------------- erc20-deploy START -------------------------
info.bridge: 0x41E686e06a29dF0Ef2cf61c2d2d0742D2d02A18b
info.token: 0xc6BcF9b6F8Fb055A6Af51C92A45699bE572ca287
info.bridge: 0x8bf2813BA01dEaEEA9191B425dbB86f3AC998aB4
info.token: 0x2b96ce1109d01ec2DA68A7bd1B6955C9d79bA343
/Users/egon/workspace/servicechain-value-transfer-examples/node_modules/caver-js/packages/caver-core-method/src/index.js:765
                new Error(`${errors.txErrorTable[txError]}\n ${receiptJSON}`),
                ^

Error: evm: execution reverted
 {
  "blockHash": "0xfd953b434ecc60f1db32f4903ddc51c5f0504931994a8f59bc74c9c7860740c8",
  "blockNumber": 32154,
  "contractAddress": null,
  "from": "0xe9858f249e639cabdb5408e78d1c7a5150869942",
  "gas": "0x5f5e100",
  "gasPrice": "0x0",
  "gasUsed": 27584,
  "input": "0x3682a450000000000000000000000000e9858f249e639cabdb5408e78d1c7a5150869942",
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "nonce": "0x9",
  "senderTxHash": "0x2cf96f1dd6998abfeffb89ad754ef30356ffb8a6245a5e284e293077d2ce29ec",
  "signatures": [
    {
      "V": "0xff1",
      "R": "0xfc11f112fbe62c8dd9c01c4665145eb1b3c4f2de661dc4b863456ba70d71791c",
      "S": "0x17358a27e0c14eaa0c4c3fbd75e1a35431e8b19cedcd61f79a0cc62399238b4c"
    }
  ],
  "status": false,
  "to": "0x41e686e06a29df0ef2cf61c2d2d0742d2d02a18b",
  "transactionHash": "0x2cf96f1dd6998abfeffb89ad754ef30356ffb8a6245a5e284e293077d2ce29ec",
  "transactionIndex": 0,
  "txError": "0x9",
  "type": "TxTypeSmartContractExecution",
  "typeInt": 48,
  "value": "0x0",
  "events": {}
}
    at checkForNormalTx (/Users/egon/workspace/servicechain-value-transfer-examples/node_modules/caver-js/packages/caver-core-method/src/index.js:765:17)
    at /Users/egon/workspace/servicechain-value-transfer-examples/node_modules/caver-js/packages/caver-core-method/src/index.js:642:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I think this code must be commented out because the operator is already registered as an operator when the bridge contract is created.
```
  for (const bridge of conf.bridges) {
    // register operator
    await conf.contract.child.newInstanceBridge.methods.registerOperator(bridge.child.operator).send({ from: conf.sender.child.address, gas: 100000000, value: 0 });
    await conf.contract.parent.newInstanceBridge.methods.registerOperator(bridge.parent.operator).send({ from: conf.sender.parent.address, gas: 100000000, value: 0 });
  }
```

**Comment by hyunsooda** [comment]
A bridge operator is not automatically registered in the deploy constructor. If an operator registration failed, a corresponding revert message is recorded. Could you attach the trace result thru `revertTracer` or `fastCallTracer`? (ref. https://klaytn.gitbook.io/docs/bapp/json-rpc/api-references/debug/tracing).

@2dvorak, please take a look.

**Comment by egonspace** [comment]
It was my mistake. It was a problem because I set the deployer and operator to the same address. I close this.
